# Last Update: 2025-09-19 01:17:46 UTC
allow-lan: true
bind-address: '*'
dns:
  enable: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fallback:
  - tls://1.1.1.1:853
  - tls://8.8.4.4:853
  ipv6: false
  listen: 0.0.0.0:7874
  nameserver:
  - 1.1.1.1
  - 8.8.8.8
external-controller: 0.0.0.0:9090
external-ui: /usr/share/openclash/ui
external-ui-name: metacubexd
log-level: info
mixed-port: 7893
mode: rule
port: 7890
profile:
  statistics: true
  store-fake-ip: true
  store-selected: true
  tracing: false
proxies:
- alterId: 0
  cipher: auto
  name: FRæ³•å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  network: ws
  port: 44579
  server: 2001:bc8:32d7:302::10
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: 8e34e170-13ae-4892-9d20-05962acc9f84
  ws-headers:
    Host: 2001:bc8:32d7:302::10
  ws-path: /
- alterId: 1
  cipher: auto
  name: FRæ³•å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 2
  network: ws
  port: 443
  server: kampong.org
  skip-cert-verify: true
  tls: true
  type: vmess
  udp: true
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  ws-headers:
    Host: kampong.org
  ws-path: linkvws
- alterId: 0
  cipher: auto
  name: GBè‹±å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  network: ws
  port: 443
  server: DdDDdddddDFrrrrrrRRy.IRan2035.dPDns.ORG
  skip-cert-verify: true
  tls: true
  type: vmess
  udp: true
  uuid: a94fafdb-10d6-46c2-be8a-5c2e8358fbb0
  ws-headers:
    Host: ddddddddddfrrrrrrrry.iran2035.dpdns.org
  ws-path: /CjJ9A46ZRHvgWvVcmjyiKVby2Lp
- alterId: 64
  cipher: auto
  name: HKé¦™æ¸¯(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  port: 34141
  server: 183.240.180.3
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
- alterId: 64
  cipher: auto
  name: HKé¦™æ¸¯(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 2
  port: 39595
  server: 183.240.245.251
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
- cipher: chacha20-ietf-poly1305
  name: JPæ—¥æœ¬(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  password: Nk9asglDzHzjktVzTkvhaA
  port: 443
  server: arxfw2b78fi2q9hzylhn.freesocks.work
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  password: 9tqhMdIrTkgQ46PvhyAtMH
  port: 443
  server: switcher-nick-croquet.freesocks.work
  type: ss
  udp: true
- alterId: 2
  cipher: auto
  name: USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 2
  network: ws
  port: 30808
  server: v8.heduian.link
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  ws-headers:
    Host: v8.heduian.link
  ws-path: /oooo
- cipher: chacha20-ietf-poly1305
  name: USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 3
  password: p78naCf2EfOlRSLTX0wFVx
  port: 443
  server: pupas-shirting-unsung.freesocks.work
  type: ss
  udp: true
- name: USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 4
  password: 2ee85121-31de-4581-a492-eb00f606e392
  port: 443
  server: 51.81.203.233
  skip-cert-verify: true
  type: trojan
  udp: true
- cipher: chacha20-ietf-poly1305
  name: USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 5
  password: XUMTygEM1jVYIvysXKqA5T
  port: 443
  server: hackney-latest-strike.freesocks.work
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: ä¹Œå…‹å…°(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  password: RFK38Cg7APneSB5cWDcpbm
  port: 443
  server: switcher-nick-croquet.freesocks.work
  type: ss
  udp: true
- alterId: 0
  cipher: auto
  name: ä¸¹éº¦(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  network: ws
  port: 80
  server: csgo.com
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: 1d9442f8-f4d6-46d0-8c81-69d4f404f8a5
  ws-headers:
    Host: cdn-node-oss-91.paofu.de
  ws-path: /profile/telegram@ssrsub
- alterId: 0
  cipher: auto
  name: ä¸¹éº¦(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 2
  network: ws
  port: 80
  server: fastcup.net
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: 1d9442f8-f4d6-46d0-8c81-69d4f404f8a5
  ws-headers:
    Host: cdn-node-oss-91.paofu.de
  ws-path: /profile/telegram@ssrsub
- alterId: 0
  cipher: auto
  name: ä¸¹éº¦(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 3
  network: ws
  port: 80
  server: pubg.ac
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: 1d9442f8-f4d6-46d0-8c81-69d4f404f8a5
  ws-headers:
    Host: cdn-node-oss-91.paofu.de
  ws-path: /profile/telegram@ssrsub
- alterId: 0
  cipher: auto
  name: ä¸¹éº¦(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 4
  network: ws
  port: 443
  server: 104.21.77.149
  skip-cert-verify: true
  tls: true
  type: vmess
  udp: true
  uuid: 86983fd3-f4da-40b3-8746-61b200eb8040
  ws-headers:
    Host: ccccvfg6yui.999834.xyz
  ws-path: /nvjx6j7kbDQIQMZvbeVA9
- alterId: 0
  cipher: auto
  name: JPæ—¥æœ¬(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 2
  network: ws
  port: 54516
  server: 158.101.146.3
  skip-cert-verify: true
  tls: true
  type: vmess
  udp: true
  uuid: 6d0b24b6-6622-44b2-8da0-ef1e67651325
  ws-headers:
    Host: serv00_vmess.sweetrx.eu.org
  ws-path: /vmess
- alterId: 0
  cipher: auto
  name: ä¸¹éº¦(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 5
  network: ws
  port: 80
  server: vn4.viefast.net
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: 9e76767d-4bfa-4f04-a800-42e2f63afed2
  ws-headers:
    Host: www.linemo.jp
  ws-path: /viefast
- alterId: 1
  cipher: auto
  name: FRæ³•å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 3
  network: ws
  port: 443
  server: serkat.org
  skip-cert-verify: true
  tls: true
  type: vmess
  udp: true
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  ws-headers:
    Host: serkat.org
  ws-path: linkvws
- alterId: 64
  cipher: auto
  name: HKé¦™æ¸¯(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 3
  port: 52512
  server: 183.240.180.47
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
proxy-groups:
- interval: 600
  name: ğŸš€ è‡ªåŠ¨é€‰æ‹©
  proxies: &id001
  - FRæ³•å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  - FRæ³•å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 2
  - GBè‹±å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  - HKé¦™æ¸¯(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  - HKé¦™æ¸¯(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 2
  - JPæ—¥æœ¬(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 2
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 3
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 4
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 5
  - ä¹Œå…‹å…°(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  - ä¸¹éº¦(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  - ä¸¹éº¦(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 2
  - ä¸¹éº¦(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 3
  - ä¸¹éº¦(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 4
  - JPæ—¥æœ¬(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 2
  - ä¸¹éº¦(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 5
  - FRæ³•å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 3
  - HKé¦™æ¸¯(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 3
  tolerance: 150
  type: url-test
  url: http://www.gstatic.com/generate_204
- name: ğŸ“± ç¤¾äº¤åª’ä½“
  proxies: *id001
  type: select
- name: ğŸ¥ è§†é¢‘åª’ä½“
  proxies: *id001
  type: select
- name: ğŸ® æ¸¸æˆåŠ é€Ÿ
  proxies: *id001
  type: select
- name: ğŸ¬ å¥ˆé£è§£é”
  proxies: *id001
  type: select
- name: ğŸ¤– ChatGPT
  proxies: *id001
  type: select
- name: ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
  proxies:
  - REJECT
  - DIRECT
  type: select
- name: âš¡ å…¨å±€ä»£ç†
  proxies:
  - ğŸš€ è‡ªåŠ¨é€‰æ‹©
  - ğŸ“± ç¤¾äº¤åª’ä½“
  - ğŸ¥ è§†é¢‘åª’ä½“
  - ğŸ® æ¸¸æˆåŠ é€Ÿ
  - ğŸ¬ å¥ˆé£è§£é”
  - ğŸ¤– ChatGPT
  - ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
  - DIRECT
  type: select
- name: ğŸ›¡ï¸ ç­–ç•¥é€‰æ‹©
  proxies:
  - âš¡ å…¨å±€ä»£ç†
  - ğŸš€ è‡ªåŠ¨é€‰æ‹©
  type: select
redir-port: 7892
rules:
- GEOIP,LAN,DIRECT
- GEOIP,CN,DIRECT
- DOMAIN,localhost,DIRECT
- DOMAIN,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- MATCH,ğŸ›¡ï¸ ç­–ç•¥é€‰æ‹©
secret: YwxHtojj
socks-port: 7891
tproxy-port: 7895
