proxy-groups:
  - name: "ğŸš€ è‡ªåŠ¨é€‰æ‹©"
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 100
    use:
      - all
  - name: "ğŸ“± ç¤¾äº¤åª’ä½“"
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 100
    use:
      - all
  - name: "ğŸ¥ è§†é¢‘åª’ä½“"
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 100
    use:
      - all
  - name: "ğŸ® æ¸¸æˆåŠ é€Ÿ"
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 80
    use:
      - all
  - name: "ğŸ¬ å¥ˆé£è§£é”"
    type: fallback
    url: http://www.netflix.com/generate_204
    interval: 300
    tolerance: 50
    use:
      - all
  - name: "ğŸ¤– ChatGPT"
    type: fallback
    url: http://chat.openai.com
    interval: 300
    tolerance: 80
    use:
      - all
  - name: "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª"
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: "âš¡ å…¨å±€ä»£ç†"
    type: select
    proxies:
      - "ğŸš€ è‡ªåŠ¨é€‰æ‹©"
      - "ğŸ“± ç¤¾äº¤åª’ä½“"
      - "ğŸ¥ è§†é¢‘åª’ä½“"
      - "ğŸ® æ¸¸æˆåŠ é€Ÿ"
      - "ğŸ¬ å¥ˆé£è§£é”"
      - "ğŸ¤– ChatGPT"
      - "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª"
      - DIRECT
  - name: "ğŸ›¡ï¸ ç­–ç•¥é€‰æ‹©"
    type: select
    proxies:
      - "âš¡ å…¨å±€ä»£ç†"
      - "ğŸš€ è‡ªåŠ¨é€‰æ‹©"
